### ISSUE TITLE
Truncation in calculation of Hermite Coefficients 

### ISSUE THREAD

**Issue by jlivsey** [jlivsey/countsFun#1]
We switched truncation maximum to be 1000. This adhoc fix should be addressed. Change is in the `HermCoefNegBin_k` function.

` N <- which(round(pnbinom(1:1000, r,p), 7) == 1)[1] ;
  if(is.na(N)){
    N=1000
  }`

**Comment by jlivsey** [comment]
@kechagias fix this

**Comment by kechagias** [comment]
The number 1000 now appears as the parameter MaxCdf that is passed as an argument. The cdf will be computed up to this number (for light tails cdf=1 fast).

I also fixed the number of HC coefficients which now appears as nHC.

Testing the effects of these parameters in Gaussian Likelihood is now easy as they can be set when the simulation is run.
