### ISSUE TITLE
Initial Estimation - All distributions

### ISSUE THREAD

**Issue by kechagias** [jlivsey/countsFun#10]
Jim I am adding a task for you, if you are too busy assign it back to me: InitialEstimates function works for Poisson and Negative Binomial. Please add initial estiamtion for the other distributions.

**Comment by kechagias** [comment]
@jlivsey I am assigning JJ to this ticket because I think he has been looking into it a bit already. @JiajieKong will you have time to work on this for Friday? If not, please assign it back to me.

**Comment by JiajieKong** [comment]
Hi Stefanos and James,

No problem. Keep this ticket open for me.

J

**Comment by kechagias** [comment]
@JiajieKong pushed his work and I have started fixing little issues on this. I am assigning this ticket to myself for now.

**Comment by kechagias** [comment]
I pushed several changes - it seems that only ZIP is left now.

**Comment by kechagias** [comment]
ZIP is also complete.
