### ISSUE TITLE
Complete development for covariates

### ISSUE THREAD

**Issue by kechagias** [jlivsey/countsFun#16]
@JiajieKong currently covariates are supported for Poisson Negative Binomial and Gen Poisson distributions. Do you want to add the other ones?
 - Binomial
 - Mixed Poisson
 - Some Zero Inflated

As we chatted the Binomial case should be straightforward (add the covariates in p to get p_t  = exp(Beta*x_t)).  For the Mixed Poisson we could do something like lambda_1 = b10 + b11*X_t, lambda_2 = b10 + b11*X_t, and keep the mixing parameter p constant but please check with Robert about that. I am assigning this to you for now to begin with Binomial, but we can adjust later down the road.

**Comment by JiajieKong** [comment]
Yep. I am gonna to meet with Robert on Tuesday and begin with the binomial one.

**Comment by JiajieKong** [comment]
No problem. I am currently working on it.

**Comment by JiajieKong** [comment]
@kechagias I just updated the "Mixed Poisson" and "ZIP" the marginal distribution and push the result online. Here is some questions I have:
1. Do you want to work on the generalized poisson distribution? I want to add it to the unit test as well but couldn't find the density function, so probably I need to have the paper of GP to fix the problem.
2. For the binomial case, it seems like the sample size n is considered to be known in our case. Dose that mean the user need to enter the exact n by themselves? If so, we need to modify the code a little bit.
3. As far as I observe, it is always hard for the "Unit_Test" to go through all the cases, since it is likely that a a error message show up in line 95, due to the "bad" AR.

**Comment by kechagias** [comment]
Hey @JiajieKong! Ty for the update!! I will check it today.
 
1. Let me work on the Generalized Poisson. I think some version of the cdfs and mass functions are already uploaded. 
2. I am not sure what you mean that the sample size is known. In the case of Bernoulli distribution, it is equal to 1. Otherwise, we model through the parametrization of the mean. To avoid this confusion please send the write up for all the parametrizations for all of our distributions with and without regressors. Then we can use these formulas as reference. Also keep in mind that we will do comparisons with the gcmr and tsmodel packages so we need to check what they are doign too. Please chat with Jim if needed on this too.
3. In the GenModelParam function I deliberately created some "bad" parameter schemes to confirm that we will receive errors or warnings that we can see in the final output of the unit test. Keep in mind that the point of the unit test is not only to run "clear" for "good" cases, but also to verify that our code returns proper errors and warnings for "bad" cases.

**Comment by JiajieKong** [comment]
Hey @kechagias, thanks for the clarification.

For the point 3, I know the you deliberately use some bad $\phi$ to test the code, I mean the error arise from line 74, which is not inside "trycatch", so the loop simply stop once a bad $\phi$ is selected.

**Comment by kechagias** [comment]
Assigning this to me to complete.

**Comment by JiajieKong** [comment]
Sure, Steve. Any timelinej/deadline for it?

**Comment by kechagias** [comment]
Hey JJ,

I have been working on finishing the R package and was simply doing some
bookkeeping, clearing up tickets.

Best,
Stefanos

**Comment by kechagias** [comment]
I pushed several changes - it seems that only ZIP is left now.

**Comment by kechagias** [comment]
Fixed ZIP. Now log(lambda) = Xb and the inflation prob is constant. In the binomial case the number of trials is considere34d to be known and the only parameter to be estimated is p as logit(p) = Xb.

**Comment by kechagias** [comment]
Also fixed Mixed Poisson.
