### ISSUE TITLE
Fix Task = "Simulation" within lgc wrapper

### ISSUE THREAD

**Issue by jlivsey** [jlivsey/countsFun#67]
Currently the `Task = "Simulation"` option does not work when called from `lgc()`

The current error I'm getting is: 

``` r
# load libraries
library(countsFun)
library(tictoc)
library(optimx)
library(ltsa)
library(itsmr)
library(numDeriv)
library(MASS)
library(parallel)
library(doParallel)

# Specify model and methods
n              = 50
Regressor      = NULL
CountDist      = "Poisson"
MargParm       = 3
ARParm         = 0.5
MAParm         = NULL
ARMAModel      = c(length(ARParm), length(MAParm))
ParticleNumber = 5
epsilon        = 0.5
EstMethod      = "PFR"
TrueParam      = c(MargParm, ARParm, MAParm)
Task           = 'Simulation'
SampleSize     = 50
nsim           = 1
no_cores       = 1
OptMethod      = "bobyqa"
OptMethod      = "L-BFGS-B"
OutputType     = "list"
ParamScheme    = NULL
maxdiff        = 10 ^ (-6)

DependentVar = 
c(5, 4, 2, 4, 1, 3, 3, 4, 4, 7, 4, 5, 7, 5, 1, 2, 2, 3, 3, 4, 
  4, 5, 4, 2, 2, 1, 1, 1, 1, 2, 0, 0, 3, 4, 6, 5, 4, 3, 2, 1, 4, 
  3, 5, 3, 1, 1, 3, 4, 6, 3)

# call the wrapper
a = lgc(
  DependentVar,
  Regressor,
  EstMethod,
  CountDist,
  ARMAModel,
  ParticleNumber,
  epsilon,
  initialParam = TrueParam,
  TrueParam,
  Task = "Simulation",
  SampleSize,
  nsim = 1,
  no_cores,
  OptMethod,
  OutputType,
  ParamScheme,
  maxdiff
)
#> Error in lgc(DependentVar, Regressor, EstMethod, CountDist, ARMAModel, : object 'FitResults' not found
```

<sup>Created on 2024-09-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by kechagias** [comment]
This may be a bit tricky to figure out. We should ice it for now, and even consider not fixing it. If we see it is too hard too fix we could remove the functionality for Simulation as this can be also done outside of the package.

**Comment by kechagias** [comment]
also I added formula syntax so the example would need to be modified as:

DependentVar = 
  c(5, 4, 2, 4, 1, 3, 3, 4, 4, 7, 4, 5, 7, 5, 1, 2, 2, 3, 3, 4, 
    4, 5, 4, 2, 2, 1, 1, 1, 1, 2, 0, 0, 3, 4, 6, 5, 4, 3, 2, 1, 4, 
    3, 5, 3, 1, 1, 3, 4, 6, 3)

# save the data in a data frame
df = data.frame(DependentVar)

# specify the regression model
formula = DependentVar~0


# call the wrapper
mylgc = lgc(formula        = formula,
            data           = df,
  EstMethod,
  CountDist,
  ARMAModel,
  ParticleNumber,
  epsilon,
  initialParam = TrueParam,
  TrueParam,
  Task = "Simulation",
  SampleSize,
  nsim = 1,
  no_cores,
  OptMethod,
  OutputType,
  ParamScheme,
  maxdiff
)

**Comment by kechagias** [comment]
I will add appropriate error handling and make this a future enhancement ticket.

**Comment by kechagias** [comment]
The example Jim gave with the small change in how the arguments are inputted is in 
C:\Users\E42069\OneDrive - National Bank of Greece S.A\Documents\countsFun2\tests\SimulationIssue
